version: '2.1'
services:
  #config servers
  mongodb-conf-rs-1:
    extends:
      file: mongo-rs.yml
      service: mongodb-rs
    volumes:
      - ./mongo-config/config-rs:/etc/mongo
      - ./mongo-data/mongodb-conf-rs-1:/data/db
      - ./mongo-logs/mongodb-conf-rs-1:/var/log/mongodb
      - ./mongo-initdb/mongo-initdb:/docker-entrypoint-initdb.d
      - ./scripts/mongo-conf-rs.init.js:/mongo-conf-rs.init.js
      - ./scripts/mongo-auth.admin.init.js:/mongo-auth.admin.init.js

  mongodb-conf-rs-2:
    extends:
      file: mongo-rs.yml
      service: mongodb-rs
    volumes:
      - ./mongo-config/config-rs:/etc/mongo
      - ./mongo-data/mongodb-conf-rs-2:/data/db
      - ./mongo-logs/mongodb-conf-rs-2:/var/log/mongodb

  mongodb-conf-rs-3:
    extends:
      file: mongo-rs.yml
      service: mongodb-rs
    volumes:
      - ./mongo-config/config-rs:/etc/mongo
      - ./mongo-data/mongodb-conf-rs-3:/data/db
      - ./mongo-logs/mongodb-conf-rs-3:/var/log/mongodb

  mongodb-sh-1-rs-1:
    extends:
      file: mongo-rs.yml
      service: mongodb-rs
    volumes:
      - ./mongo-config/shard-1-rs:/etc/mongo
      - ./mongo-data/mongodb-sh-1-rs-1:/data/db
      - ./mongo-logs/mongodb-sh-1-rs-1:/var/log/mongodb
      - ./mongo-initdb/mongo-initdb:/docker-entrypoint-initdb.d
      - ./scripts/mongo-sh-1-rs.init.js:/mongo-sh-1-rs.init.js

  mongodb-sh-1-rs-2:
    extends:
      file: mongo-rs.yml
      service: mongodb-rs
    volumes:
      - ./mongo-config/shard-1-rs:/etc/mongo
      - ./mongo-data/mongodb-sh-1-rs-2:/data/db
      - ./mongo-logs/mongodb-sh-1-rs-2:/var/log/mongodb

  mongodb-sh-1-rs-3:
    extends:
      file: mongo-rs.yml
      service: mongodb-rs
    volumes:
      - ./mongo-config/shard-1-rs:/etc/mongo
      - ./mongo-data/mongodb-sh-1-rs-3:/data/db
      - ./mongo-logs/mongodb-sh-1-rs-3:/var/log/mongodb

  mongodb-sh-2-rs-1:
    extends:
      file: mongo-rs.yml
      service: mongodb-rs
    volumes:
      - ./mongo-config/shard-2-rs:/etc/mongo
      - ./mongo-data/mongodb-sh-2-rs-1:/data/db
      - ./mongo-logs/mongodb-sh-2-rs-1:/var/log/mongodb
      - ./mongo-initdb/mongo-initdb:/docker-entrypoint-initdb.d
      - ./scripts/mongo-sh-2-rs.init.js:/mongo-sh-2-rs.init.js

  mongodb-sh-2-rs-2:
    extends:
      file: mongo-rs.yml
      service: mongodb-rs
    volumes:
      - ./mongo-config/shard-2-rs:/etc/mongo
      - ./mongo-data/mongodb-sh-2-rs-2:/data/db
      - ./mongo-logs/mongodb-sh-2-rs-2:/var/log/mongodb

  mongodb-sh-2-rs-3:
    extends:
      file: mongo-rs.yml
      service: mongodb-rs
    volumes:
      - ./mongo-config/shard-2-rs:/etc/mongo
      - ./mongo-data/mongodb-sh-2-rs-3:/data/db
      - ./mongo-logs/mongodb-sh-2-rs-3:/var/log/mongodb

  # mongos
  mongos-1:
    extends:
      file: mongo-rs.yml
      service: mongodb-rs
    command:
      - mongos
      - "--port"
      - "27017"
      - "--configdb"
      - "config-rs/mongodb-conf-rs-1:27019,mongodb-conf-rs-2:27019,mongodb-conf-rs-3:27019"
      - "--bind_ip_all"
      # - "--fork"
      - "--logpath"
      - "/var/log/mongodb/mongos.log"
      - "--keyFile"
      - "/etc/mongo/secrets/mongo.key"
    volumes:
      - ./mongo-logs/mongos-1:/var/log/mongodb
      - ./scripts/mongo-sharding.init.js:/mongo-sharding.init.js
      - ./scripts/mongo-auth.admin.init.js:/mongo-auth.admin.init.js
    # command: mongos --configdb config-rs/mongodb-conf-rs-1:27019,mongodb-conf-rs-2:27019,mongodb-conf-rs-3:27019 --keyFile /etc/mongo/secrets/mongo.key
    ports:
     - "27017:27017"
    depends_on:
      - mongodb-conf-rs-1
      - mongodb-conf-rs-2
      - mongodb-conf-rs-3
      - mongodb-sh-1-rs-1
      - mongodb-sh-1-rs-2
      - mongodb-sh-1-rs-3
      - mongodb-sh-2-rs-1
      - mongodb-sh-2-rs-2
      - mongodb-sh-2-rs-3

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.124.0/28
  # proxy-tier:
  #   external:
  #     name: proxy_default
