version: '2.1'
services:
  #config servers
  mongodb-conf-rs-1:
    extends:
      file: mongo-rs.yml
      service: mongodb-conf-rs
    volumes:
      - ./mongo-config/config-rs:/etc/mongo
      - ./mongo-data/mongodb-conf-rs-1:/data/db
      - ./mongo-logs/mongodb-conf-rs-1:/var/log/mongodb
      - ./mongo-initdb/mongo-initdb:/docker-entrypoint-initdb.d
      - ./scripts/mongo-conf-rs.init.js:/mongo-conf-rs.init.js

  mongodb-conf-rs-2:
    extends:
      file: mongo-rs.yml
      service: mongodb-conf-rs
    volumes:
      - ./mongo-config/config-rs:/etc/mongo
      - ./mongo-data/mongodb-conf-rs-2:/data/db
      - ./mongo-logs/mongodb-conf-rs-2:/var/log/mongodb

  mongodb-conf-rs-3:
    extends:
      file: mongo-rs.yml
      service: mongodb-conf-rs
    volumes:
      - ./mongo-config/config-rs:/etc/mongo
      - ./mongo-data/mongodb-conf-rs-3:/data/db
      - ./mongo-logs/mongodb-conf-rs-3:/var/log/mongodb

  # Mongo router
  # mongos-router-1:
  #   image: mongo:4.0
  #   command: mongos --port 27018 --configdb config-rs/mongodb-conf-rs-1:27017,mongodb-conf-rs-2:27017,mongodb-conf-rs-3:27017 --keyFile /etc/mongo.key
  #   volumes:
  #       - ${PWD}/mongo-utils/mongodb.key:/etc/mongo.key
  #   ports:
  #    - "27017:27017"
  #   networks:
  #     - default
  #   depends_on:
  #     - mongodb-conf-rs-1
  #     - mongodb-conf-rs-2
  #     - mongodb-conf-rs-3

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.124.0/28
  # proxy-tier:
  #   external:
  #     name: proxy_default
