version: '2.1'
services:
  mongodb-rs:
    image: mongo:4.0
    volumes:
      - ./mongo-secrets:/etc/mongo/secrets
    mem_limit: 1g
    memswap_limit: 0
    mem_swappiness: 0
    networks:
      - default
    # command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
    command: ["mongod", "--config", "/etc/mongo/mongod.conf", "--setParameter", "honorSystemUmask=true"]